openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /{id}:
    put:
      tags:
        - person-controller
      operationId: updatePerson
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonDTO'
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: object
    patch:
      tags:
        - person-controller
      operationId: partialUpdatePerson
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonDTO'
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /:
    post:
      tags:
        - person-controller
      operationId: savePerson_1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonDTO'
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /person:
    get:
      tags:
        - person-controller
      operationId: getPersons
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /person/{id}:
    get:
      tags:
        - person-controller
      operationId: getOnePerson
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: object
    delete:
      tags:
        - person-controller
      operationId: deletePerson
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /person/{id}/salary:
    get:
      tags:
        - person-controller
      operationId: getSalaryPerson
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: output
          in: query
          required: true
          schema:
            type: string
            enum:
              - min
              - full
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /person/{id}/age:
    get:
      tags:
        - person-controller
      operationId: getAgePerson
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: output
          in: query
          required: true
          schema:
            type: string
            enum:
              - days
              - months
              - years
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    PersonDTO:
      type: object
      properties:
        name:
          type: string
        birthDate:
          type: string
          format: date
        hireDate:
          type: string
          format: date